server.port=8080
spring.data.mongodb.uri=mongodb+srv://Priyu:Priyu223@cluster0.rc0acrb.mongodb.net/expense_tracker?retryWrites=true&w=majority
smartexpense.jwtExpirationMs=86400000
smartexpense.jwtSecret=SmartExpenseTrackingSecretKeyForJWTAuthentication256Bits
logging.level.com.smartexpense.backend=DEBUG
logging.level.org.springframework.security=DEBUG
